playing_with_duckdb:
  outputs:
    s3:
      type: duckdb
      path: dev.duckdb
      schema: analytics
      extensions:
        - httpfs
        - parquet

      threads: 1

    motherduck:
      type: duckdb
      extensions:
        - httpfs
        - parquet


      schema: analytics
      threads: 4

  target: s3

