playing_with_duckdb:
  outputs:
    gmdata_s3:
      type: duckdb
      path: dev.duckdb
      schema: analytics
      extensions:
        - httpfs
        - parquet
      settings:
        s3_region: "{{ env_var('GMDATA_S3_REGION') }}"
        s3_access_key_id: "{{ env_var('GMDATA_S3_ACCESS_KEY') }}"
        s3_secret_access_key: "{{ env_var('GMDATA_S3_SECRET_KEY') }}"
      threads: 1

    motherduck:
      type: duckdb
      extensions:
        - httpfs
        - parquet
      settings:
        s3_region: "{{ env_var('GMDATA_S3_REGION') }}"
        s3_access_key_id: "{{ env_var('GMDATA_S3_ACCESS_KEY') }}"
        s3_secret_access_key: "{{ env_var('GMDATA_S3_SECRET_KEY') }}"
      path: "{{ env_var('MOTHERDUCK_TOKEN') }}"
      schema: analytics
      threads: 4

  target: gmdata_s3

